#version: "3.8"

services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: healthsphere
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build: ./services/user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres-db
    env_file:
      - ./services/user-service/.env
    environment:
      - DB_NAME=healthsphere
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres-db
      - JWT_SECRET=supersecretjwt

  doctor-service:
    build: ./services/doctor-service
    ports:
      - "8082:8082"
    env_file:
      - ./services/doctor-service/.env
    depends_on:
      - postgres-db
    volumes:
      - ./services/doctor-service/uploads:/app/uploads

  appointment-service:
    build: ./services/appointment-service
    ports:
      - "8083:8083"
    env_file:
      - ./services/appointment-service/.env
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=healthsphere
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=supersecretjwt
    depends_on:
      - postgres-db
    
  communication-service:
    build: ./services/communication-service
    ports:
      - "8084:8084"
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=healthsphere
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=supersecretjwt
      - USER_SERVICE_URL=http://user-service:8081
      - FRONTEND_URL=http://localhost:3001
    depends_on:
      - postgres-db


  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - USER_SERVICE_URL=http://user-service:8081
      - FRONTEND_URL=http://localhost:3001
    depends_on:
      - user-service

volumes:
  pgdata:
